import { Product, Category, Review, MysteryCase } from './types';

export const categories: Category[] = [
  { id: 'shooters', name: 'Шутеры', icon: '🎯', count: 48, color: '#EF4444' },
  { id: 'rpg', name: 'RPG', icon: '⚔️', count: 62, color: '#7C3AED' },
  { id: 'strategy', name: 'Стратегии', icon: '🏰', count: 35, color: '#F59E0B' },
  { id: 'sports', name: 'Спорт', icon: '⚽', count: 29, color: '#10B981' },
  { id: 'horror', name: 'Хоррор', icon: '👻', count: 21, color: '#6B7280' },
  { id: 'racing', name: 'Гонки', icon: '🏎️', count: 18, color: '#06B6D4' },
  { id: 'adventure', name: 'Приключения', icon: '🗺️', count: 44, color: '#F97316' },
  { id: 'fighting', name: 'Файтинги', icon: '🥊', count: 15, color: '#EC4899' },
];

export const products: Product[] = [
  {
    id: '1',
    title: 'Cyberpunk 2077',
    subtitle: 'Ultimate Edition',
    price: 249000,
    originalPrice: 349000,
    discount: 29,
    image: 'https://picsum.photos/seed/cyber2077/400/550',
    category: 'rpg',
    platform: ['PC', 'PS5', 'Xbox'],
    rating: 4.8,
    reviews: 2847,
    badge: 'sale',
    inStock: true,
    description: 'Откройте для себя мегаполис будущего в этом открытом мире от создателей The Witcher 3. Полное издание включает все DLC.',
    features: ['Открытый мир', 'Киберпанк-атмосфера', 'Глубокий сюжет', 'Моды'],
    tags: ['openworld', 'rpg', 'cyberpunk', 'cdprojektred'],
  },
  {
    id: '2',
    title: 'Elden Ring',
    subtitle: 'Shadow of the Erdtree',
    price: 299000,
    image: 'https://picsum.photos/seed/eldenring/400/550',
    category: 'rpg',
    platform: ['PC', 'PS5', 'Xbox'],
    rating: 4.9,
    reviews: 5231,
    badge: 'hot',
    inStock: true,
    description: 'Эпическое фэнтезийное приключение от FromSoftware и Джорджа Р.Р. Мартина. Величайшая RPG поколения.',
    features: ['Открытый мир', 'Сложный геймплей', 'Мультиплеер', 'Богатый лор'],
    tags: ['soulslike', 'rpg', 'fantasy', 'fromsoftware'],
  },
  {
    id: '3',
    title: 'Call of Duty',
    subtitle: 'Modern Warfare III',
    price: 189000,
    originalPrice: 249000,
    discount: 24,
    image: 'https://picsum.photos/seed/codmw3/400/550',
    category: 'shooters',
    platform: ['PC', 'PS5', 'Xbox'],
    rating: 4.2,
    reviews: 8920,
    badge: 'sale',
    inStock: true,
    description: 'Вернитесь на поля сражений с новым арсеналом, картами и режимами. Варзон 3 включён.',
    features: ['Multiplayer', 'Warzone', 'Zombies', 'Campaign'],
    tags: ['fps', 'shooter', 'multiplayer', 'activision'],
  },
  {
    id: '4',
    title: 'GTA VI',
    subtitle: 'Standard Edition',
    price: 399000,
    image: 'https://picsum.photos/seed/gtavi/400/550',
    category: 'adventure',
    platform: ['PS5', 'Xbox'],
    rating: 5.0,
    reviews: 312,
    badge: 'new',
    inStock: true,
    description: 'Величайший открытый мир в истории видеоигр. Возвращение в Vice City с новой историей.',
    features: ['Открытый мир', 'Онлайн', 'Гиперреализм', 'Два протагониста'],
    tags: ['openworld', 'crime', 'rockstar', 'gtaonline'],
  },
  {
    id: '5',
    title: 'Baldur\'s Gate 3',
    subtitle: 'Deluxe Edition',
    price: 279000,
    originalPrice: 329000,
    discount: 15,
    image: 'https://picsum.photos/seed/bg3/400/550',
    category: 'rpg',
    platform: ['PC', 'PS5'],
    rating: 4.9,
    reviews: 3445,
    badge: 'hot',
    inStock: true,
    description: 'Лучшая RPG 2023 года. Тысячи часов контента, бесконечные возможности выбора.',
    features: ['Turn-based', 'Co-op', 'D&D система', 'Моды'],
    tags: ['rpg', 'fantasy', 'turnbased', 'larian'],
  },
  {
    id: '6',
    title: 'FIFA 25',
    subtitle: 'Ultimate Team Edition',
    price: 219000,
    image: 'https://picsum.photos/seed/fifa25/400/550',
    category: 'sports',
    platform: ['PC', 'PS5', 'Xbox'],
    rating: 4.3,
    reviews: 6780,
    badge: 'new',
    inStock: true,
    description: 'Новый сезон футбола с улучшенной физикой, новыми режимами и Ultimate Team.',
    features: ['Ultimate Team', 'Career Mode', 'Pro Clubs', 'VOLTA'],
    tags: ['sports', 'football', 'ea', 'ultimate-team'],
  },
  {
    id: '7',
    title: 'Resident Evil 4',
    subtitle: 'Remake Gold Edition',
    price: 199000,
    originalPrice: 249000,
    discount: 20,
    image: 'https://picsum.photos/seed/re4/400/550',
    category: 'horror',
    platform: ['PC', 'PS5', 'Xbox'],
    rating: 4.8,
    reviews: 2156,
    badge: 'sale',
    inStock: true,
    description: 'Культовый хоррор переосмыслён для нового поколения с фотореалистичной графикой.',
    features: ['Survival Horror', 'RE Engine', 'Ada DLC', 'VR Mode'],
    tags: ['horror', 'survival', 'capcom', 'remake'],
  },
  {
    id: '8',
    title: 'Forza Horizon 5',
    subtitle: 'Premium Bundle',
    price: 229000,
    image: 'https://picsum.photos/seed/forza5/400/550',
    category: 'racing',
    platform: ['PC', 'Xbox'],
    rating: 4.7,
    reviews: 4321,
    badge: 'exclusive',
    inStock: true,
    description: 'Лучшая гоночная игра всех времён. Мексика, более 500 автомобилей и безграничная свобода.',
    features: ['Open World', '500+ Cars', 'Online', 'Seasons'],
    tags: ['racing', 'openworld', 'xbox', 'microsoft'],
  },
];

export const trendingProducts = products.slice(0, 6);
export const dailyDeals = products.filter(p => p.discount && p.discount > 0);

export const mysteryCases: MysteryCase[] = [
  {
    id: 'silver',
    title: 'Серебряный Кейс',
    price: 49000,
    image: 'https://picsum.photos/seed/case-silver/300/300',
    items: ['Случайная игра', 'Скидка 20%', 'Arcane Coins x50'],
    color: 'from-gray-400 to-gray-600',
  },
  {
    id: 'gold',
    title: 'Золотой Кейс',
    price: 99000,
    image: 'https://picsum.photos/seed/case-gold/300/300',
    items: ['AAA игра', 'DLC бонус', 'Arcane Coins x150'],
    color: 'from-yellow-400 to-amber-600',
  },
  {
    id: 'arcane',
    title: 'Arcane Кейс',
    price: 199000,
    image: 'https://picsum.photos/seed/case-phantom/300/300',
    items: ['Эксклюзивная игра', 'Годовой пропуск', 'Arcane Coins x500'],
    color: 'from-purple-500 to-cyan-500',
  },
];

export const reviews: Review[] = [
  {
    id: '1',
    author: 'Бобур Хасанов',
    avatar: 'https://picsum.photos/seed/user1/100/100',
    rating: 5,
    text: 'Arcane.uz — лучший магазин игр в Узбекистане! Мгновенная доставка ключей, хорошие цены. Elden Ring получил за 2 минуты после оплаты.',
    date: '15 мая 2025',
    verified: true,
    productName: 'Elden Ring',
  },
  {
    id: '2',
    author: 'Камила Юсупова',
    avatar: 'https://picsum.photos/seed/user2/100/100',
    rating: 5,
    text: 'Заказывала Cyberpunk 2077 — всё пришло мгновенно. Поддержка в Telegram ответила за 5 минут. Очень довольна!',
    date: '10 мая 2025',
    verified: true,
    productName: 'Cyberpunk 2077',
  },
  {
    id: '3',
    author: 'Алишер Каримов',
    avatar: 'https://picsum.photos/seed/user3/100/100',
    rating: 5,
    text: 'Покупаю здесь уже год. Mystery Cases — это огонь! Получил GTA V и ещё 3 игры за цену одного кейса.',
    date: '5 мая 2025',
    verified: true,
    productName: 'Arcane Кейс',
  },
  {
    id: '4',
    author: 'Нилуфар Рашидова',
    avatar: 'https://picsum.photos/seed/user4/100/100',
    rating: 4,
    text: 'Отличный сервис и красивый сайт. Arcane Coins выгодная система — накопила и взяла BG3 со скидкой 30%.',
    date: '1 мая 2025',
    verified: true,
    productName: 'Baldur\'s Gate 3',
  },
  {
    id: '5',
    author: 'Жавлон Мирзаев',
    avatar: 'https://picsum.photos/seed/user5/100/100',
    rating: 5,
    text: 'Лучший магазин! Купил Forza Horizon 5 на Xbox — ключ пришёл мгновенно. Буду постоянным покупателем.',
    date: '28 апреля 2025',
    verified: true,
    productName: 'Forza Horizon 5',
  },
  {
    id: '6',
    author: 'Дилноза Турсунова',
    avatar: 'https://picsum.photos/seed/user6/100/100',
    rating: 5,
    text: 'Arcane.uz — это отдельная эстетика! Купила FIFA 25 для мужа на день рождения, очень удобно оплачивать через Payme.',
    date: '22 апреля 2025',
    verified: true,
    productName: 'FIFA 25',
  },
];

export const platforms = ['PC', 'PS5', 'Xbox', 'Nintendo Switch'];
export const priceRanges = [
  { label: 'До 100 000 сум', min: 0, max: 100000 },
  { label: '100 000 — 200 000 сум', min: 100000, max: 200000 },
  { label: '200 000 — 300 000 сум', min: 200000, max: 300000 },
  { label: 'Свыше 300 000 сум', min: 300000, max: Infinity },
];
