import { Product, Category, Review, MysteryCase } from './types';

export const categories: Category[] = [
  { id: 'action',     name: 'Экшен',         icon: '⚡', count: 42, color: '#EF4444' },
  { id: 'rpg',        name: 'RPG',            icon: '⚔️', count: 62, color: '#7C3AED' },
  { id: 'openworld',  name: 'Открытый мир',   icon: '🌍', count: 31, color: '#F59E0B' },
  { id: 'multiplayer',name: 'Мультиплеер',    icon: '🎮', count: 47, color: '#06B6D4' },
  { id: 'horror',     name: 'Хоррор',         icon: '👻', count: 21, color: '#6B7280' },
  { id: 'sports',     name: 'Спорт',          icon: '⚽', count: 29, color: '#10B981' },
  { id: 'indie',      name: 'Инди',           icon: '🎨', count: 33, color: '#EC4899' },
  { id: 'racing',     name: 'Гонки',          icon: '🏎️', count: 18, color: '#3B82F6' },
];

export const products: Product[] = [
  {
    id: 'cyberpunk-2077',
    title: 'Cyberpunk 2077',
    subtitle: 'Ultimate Edition',
    price: 249000,
    originalPrice: 349000,
    discount: 29,
    image: 'https://picsum.photos/seed/cyber2077/400/550',
    screenshots: [
      'https://picsum.photos/seed/cyber2077_s1/800/450',
      'https://picsum.photos/seed/cyber2077_s2/800/450',
      'https://picsum.photos/seed/cyber2077_s3/800/450',
      'https://picsum.photos/seed/cyber2077_s4/800/450',
    ],
    category: 'rpg',
    platform: ['Steam', 'Epic Games', 'PS5', 'Xbox'],
    rating: 4.8,
    reviews: 2847,
    badge: 'sale',
    inStock: true,
    featured: true,
    developer: 'CD Projekt RED',
    publisher: 'CD Projekt',
    releaseDate: '2020-12-10',
    genres: ['RPG', 'Action', 'Open World'],
    region: 'RU/CIS',
    multiplayer: false,
    singleplayer: true,
    controllerSupport: true,
    deliveryType: 'instant',
    description: 'Откройте для себя мегаполис будущего в этом открытом мире от создателей The Witcher 3. Полное издание включает все DLC, в том числе масштабное дополнение Phantom Liberty.',
    features: ['Открытый мир', 'Киберпанк-атмосфера', 'Глубокий сюжет', 'Phantom Liberty DLC', 'Моды Steam'],
    tags: ['openworld', 'rpg', 'cyberpunk', 'cdprojektred'],
    editions: [
      {
        id: 'standard',
        title: 'Standard Edition',
        price: 179000,
        includes: ['Базовая игра', 'Цифровой OST', 'Обои и аватары'],
        badge: '',
        color: '#6B7280',
      },
      {
        id: 'ultimate',
        title: 'Ultimate Edition',
        price: 249000,
        originalPrice: 349000,
        discount: 29,
        isRecommended: true,
        isCurrentEdition: true,
        includes: ['Базовая игра', 'Phantom Liberty DLC', 'Цифровой OST', 'Артбук PDF', 'Саундтрек 2 часть', 'Комиксы (цифровой)'],
        badge: 'РЕКОМЕНДУЕМ',
        color: '#7C3AED',
      },
    ],
    requirements: {
      minimum: {
        os: 'Windows 10 64-bit',
        cpu: 'Intel Core i7-6700K / AMD Ryzen 5 1600',
        gpu: 'NVIDIA GTX 1060 6GB / AMD RX 5500 XT 8GB',
        ram: '12 GB',
        storage: '70 GB SSD',
        directx: 'DirectX 12',
      },
      recommended: {
        os: 'Windows 10/11 64-bit',
        cpu: 'Intel Core i7-8700K / AMD Ryzen 7 3700X',
        gpu: 'NVIDIA RTX 2060 Super / AMD RX 5700 XT',
        ram: '16 GB',
        storage: '70 GB SSD (NVMe)',
        directx: 'DirectX 12',
        notes: 'SSD требуется для стримирования открытого мира',
      },
    },
    productReviews: [
      {
        id: 'r1', author: 'Бобур Х.', avatar: 'https://picsum.photos/seed/rev1/80/80',
        rating: 5, text: 'Потрясающая игра! Phantom Liberty — это просто шедевр. Ключ пришёл за 2 минуты, всё активировалось без проблем.',
        date: '10 мая 2025', verified: true, playtime: '120+ часов', helpful: 42, platform: 'Steam',
      },
      {
        id: 'r2', author: 'Камила Ю.', avatar: 'https://picsum.photos/seed/rev2/80/80',
        rating: 5, text: 'Купила Ultimate Edition — получила ключ мгновенно. Игра просто невероятная, графика поразила. Рекомендую всем!',
        date: '5 мая 2025', verified: true, playtime: '85 часов', helpful: 31, platform: 'Steam',
      },
      {
        id: 'r3', author: 'Жавлон М.', avatar: 'https://picsum.photos/seed/rev3/80/80',
        rating: 4, text: 'Отличная игра, особенно после патчей 2.0. Поддержка Arcane.uz помогла с активацией — всё чётко и быстро.',
        date: '28 апр. 2025', verified: true, playtime: '60 часов', helpful: 18, platform: 'Epic Games',
      },
      {
        id: 'r4', author: 'Алишер К.', avatar: 'https://picsum.photos/seed/rev4/80/80',
        rating: 5, text: 'Самая красивая игра, в которую я играл. RTX + path tracing — это нечто невероятное. Ключ получил сразу.',
        date: '20 апр. 2025', verified: true, playtime: '200+ часов', helpful: 67, platform: 'Steam',
      },
    ],
    faq: [
      { id: 'f1', question: 'Это RU/CIS версия игры?', answer: 'Да, все ключи Cyberpunk 2077 в нашем магазине предназначены для региона RU/CIS. Игра полностью поддерживает русский язык включая озвучку.' },
      { id: 'f2', question: 'Как быстро я получу ключ?', answer: 'Instant Delivery — ключ отправляется автоматически на ваш email в течение 1–5 минут после подтверждения оплаты. Работает 24/7.' },
      { id: 'f3', question: 'Нужен ли VPN для активации?', answer: 'Нет, VPN не требуется. Ключи RU/CIS активируются напрямую через Steam или Epic Games без дополнительных инструментов.' },
      { id: 'f4', question: 'Можно ли вернуть деньги?', answer: 'Мы гарантируем работоспособность ключа. Если ключ не активируется — заменим или вернём деньги. Обратитесь в поддержку Telegram.' },
      { id: 'f5', question: 'Включает ли Ultimate Edition DLC?', answer: 'Да! Ultimate Edition включает базовую игру и DLC Phantom Liberty — самое масштабное дополнение, добавляющее 20+ часов сюжета.' },
      { id: 'f6', question: 'Можно ли предзагрузить игру?', answer: 'Cyberpunk 2077 уже выпущен, поэтому предзагрузка недоступна. После активации ключа вы можете сразу начать скачивать через Steam или Epic.' },
    ],
  },
  {
    id: 'elden-ring',
    title: 'Elden Ring',
    subtitle: 'Shadow of the Erdtree',
    price: 299000,
    image: 'https://picsum.photos/seed/eldenring/400/550',
    screenshots: [
      'https://picsum.photos/seed/eldenring_s1/800/450',
      'https://picsum.photos/seed/eldenring_s2/800/450',
      'https://picsum.photos/seed/eldenring_s3/800/450',
      'https://picsum.photos/seed/eldenring_s4/800/450',
    ],
    category: 'rpg',
    platform: ['Steam', 'PS5', 'Xbox'],
    rating: 4.9,
    reviews: 5231,
    badge: 'hot',
    inStock: true,
    featured: true,
    developer: 'FromSoftware',
    publisher: 'Bandai Namco',
    releaseDate: '2022-02-25',
    genres: ['RPG', 'Action', 'Soulslike'],
    region: 'RU/CIS',
    multiplayer: true,
    singleplayer: true,
    controllerSupport: true,
    deliveryType: 'instant',
    description: 'Эпическое фэнтезийное приключение от FromSoftware и Джорджа Р.Р. Мартина. Величайшая RPG поколения — с Shadow of the Erdtree, самым масштабным DLC в истории серии.',
    features: ['Открытый мир', 'Сложный геймплей', 'Кооператив', 'Shadow of the Erdtree', 'Богатый лор'],
    tags: ['soulslike', 'rpg', 'fantasy', 'fromsoftware'],
    editions: [
      {
        id: 'standard',
        title: 'Base Game',
        price: 219000,
        includes: ['Базовая игра Elden Ring'],
        color: '#6B7280',
      },
      {
        id: 'shadow',
        title: 'Shadow of the Erdtree',
        price: 299000,
        isRecommended: true,
        isCurrentEdition: true,
        includes: ['Базовая игра Elden Ring', 'DLC Shadow of the Erdtree', 'Новые регионы и боссы', '8+ часов сюжета'],
        badge: 'ПОЛНОЕ ИЗДАНИЕ',
        color: '#7C3AED',
      },
    ],
    requirements: {
      minimum: {
        os: 'Windows 10/11',
        cpu: 'Intel Core i5-8600K / AMD Ryzen 5 3600X',
        gpu: 'NVIDIA GTX 1070 8GB / AMD RX 5700 8GB',
        ram: '12 GB',
        storage: '60 GB SSD',
        directx: 'DirectX 12',
      },
      recommended: {
        os: 'Windows 10/11',
        cpu: 'Intel Core i7-8700K / AMD Ryzen 7 3700X',
        gpu: 'NVIDIA RTX 2080 / AMD RX 6700 XT',
        ram: '16 GB',
        storage: '60 GB SSD',
        directx: 'DirectX 12',
      },
    },
    productReviews: [
      {
        id: 'r1', author: 'Темур А.', avatar: 'https://picsum.photos/seed/er1/80/80',
        rating: 5, text: 'Лучшая игра поколения. Shadow of the Erdtree — это просто шедевр. Ключ получил мгновенно, всё прошло без проблем.',
        date: '12 мая 2025', verified: true, playtime: '300+ часов', helpful: 95, platform: 'Steam',
      },
      {
        id: 'r2', author: 'Нилуфар Р.', avatar: 'https://picsum.photos/seed/er2/80/80',
        rating: 5, text: 'Потрясающий DLC! Arcane.uz — отличный магазин, всё быстро и надёжно.',
        date: '8 мая 2025', verified: true, playtime: '150 часов', helpful: 43, platform: 'Steam',
      },
    ],
    faq: [
      { id: 'f1', question: 'Это RU/CIS версия?', answer: 'Да, ключ предназначен для региона RU/CIS. Полный русский интерфейс и субтитры.' },
      { id: 'f2', question: 'Включает ли DLC Shadow of the Erdtree?', answer: 'Текущее издание включает полный пакет: базовую игру + Shadow of the Erdtree DLC.' },
      { id: 'f3', question: 'Нужен ли VPN?', answer: 'Нет, VPN не нужен. Ключ активируется в Steam напрямую без дополнительных инструментов.' },
      { id: 'f4', question: 'Поддерживается ли кооператив?', answer: 'Да, Elden Ring поддерживает онлайн-кооператив до 4 игроков и PvP инвазии.' },
    ],
  },
  {
    id: 'gta-v',
    title: 'Grand Theft Auto V',
    subtitle: 'Premium Edition',
    price: 149000,
    originalPrice: 189000,
    discount: 21,
    image: 'https://picsum.photos/seed/gtav_cover/400/550',
    screenshots: [
      'https://picsum.photos/seed/gtav_s1/800/450',
      'https://picsum.photos/seed/gtav_s2/800/450',
      'https://picsum.photos/seed/gtav_s3/800/450',
      'https://picsum.photos/seed/gtav_s4/800/450',
    ],
    category: 'openworld',
    platform: ['Steam', 'Epic Games'],
    rating: 4.7,
    reviews: 18420,
    badge: 'sale',
    inStock: true,
    featured: true,
    developer: 'Rockstar Games',
    releaseDate: '2015-04-14',
    deliveryType: 'steam_gift',
    deliveryDescription: 'GTA V отправляется как подарок Steam. Добавьте менеджера в друзья и получите игру в течение 1–3 часов после оплаты.',
    description: 'Культовый открытый мир — Los Santos, три протагониста, GTA Online и бесконечные возможности. Самая продаваемая игра в истории.',
    features: ['GTA Online', 'Три протагониста', 'Открытый мир', 'Моды', 'Story Mode'],
    tags: ['openworld', 'crime', 'rockstar', 'multiplayer'],
  },
  {
    id: 'rdr2',
    title: 'Red Dead Redemption 2',
    subtitle: 'Ultimate Edition',
    price: 219000,
    image: 'https://picsum.photos/seed/rdr2_cover/400/550',
    screenshots: [
      'https://picsum.photos/seed/rdr2_s1/800/450',
      'https://picsum.photos/seed/rdr2_s2/800/450',
      'https://picsum.photos/seed/rdr2_s3/800/450',
      'https://picsum.photos/seed/rdr2_s4/800/450',
    ],
    category: 'openworld',
    platform: ['Steam', 'Epic Games'],
    rating: 4.9,
    reviews: 9840,
    badge: 'hot',
    inStock: true,
    featured: true,
    developer: 'Rockstar Games',
    releaseDate: '2019-11-05',
    deliveryType: 'steam_gift',
    deliveryDescription: 'RDR2 отправляется как подарок Steam на ваш аккаунт. Добавьте нашего менеджера в друзья в Steam.',
    description: 'Эпическое приключение в эпоху заката Дикого Запада. Артур Морган и банда Ван дер Линде против меняющегося мира — одна из лучших историй в видеоиграх.',
    features: ['Открытый мир', 'Кинематографичный сюжет', 'Red Dead Online', 'Детальная симуляция', '60+ часов'],
    tags: ['openworld', 'western', 'rockstar', 'story'],
  },
  {
    id: 'black-myth-wukong',
    title: 'Black Myth: Wukong',
    subtitle: 'Standard Edition',
    price: 359000,
    image: 'https://picsum.photos/seed/wukong_cover/400/550',
    screenshots: [
      'https://picsum.photos/seed/wukong_s1/800/450',
      'https://picsum.photos/seed/wukong_s2/800/450',
      'https://picsum.photos/seed/wukong_s3/800/450',
      'https://picsum.photos/seed/wukong_s4/800/450',
    ],
    category: 'action',
    platform: ['Steam', 'PS5'],
    rating: 4.8,
    reviews: 6720,
    badge: 'hot',
    inStock: true,
    featured: true,
    developer: 'Game Science',
    publisher: 'Game Science',
    releaseDate: '2024-08-20',
    genres: ['Action', 'Soulslike', 'Mythology'],
    region: 'Global',
    multiplayer: false,
    singleplayer: true,
    controllerSupport: true,
    deliveryType: 'instant',
    description: 'Первая крупная китайская AAA-игра. Основана на классике «Путешествие на Запад» — боевая система уровня ААА, потрясающая графика на Unreal Engine 5.',
    features: ['Unreal Engine 5', 'Боевые трансформации', 'Мифология', 'Boss Rush', 'Ray Tracing'],
    tags: ['action', 'soulslike', 'mythology', 'gamescience'],
    requirements: {
      minimum: {
        os: 'Windows 10 64-bit',
        cpu: 'Intel Core i7-9700 / AMD Ryzen 5 5500',
        gpu: 'NVIDIA RTX 2060 / AMD RX 5700 XT',
        ram: '16 GB',
        storage: '130 GB SSD',
        directx: 'DirectX 12',
      },
      recommended: {
        os: 'Windows 10/11 64-bit',
        cpu: 'Intel Core i7-9700K / AMD Ryzen 5 5600X',
        gpu: 'NVIDIA RTX 2080 Super / AMD RX 6800',
        ram: '16 GB',
        storage: '130 GB NVMe SSD',
        directx: 'DirectX 12',
        notes: 'Ray Tracing требует NVIDIA RTX 20xx или новее',
      },
    },
    productReviews: [
      {
        id: 'r1', author: 'Санжар Б.', avatar: 'https://picsum.photos/seed/wk1/80/80',
        rating: 5, text: 'Визуально это лучшая игра 2024 года. Боевая система просто восхитительна. Ключ Steam получил мгновенно!',
        date: '15 мая 2025', verified: true, playtime: '80 часов', helpful: 78, platform: 'Steam',
      },
      {
        id: 'r2', author: 'Дилнора Т.', avatar: 'https://picsum.photos/seed/wk2/80/80',
        rating: 5, text: 'Невероятная игра. Боссы — шедевры дизайна. Arcane.uz как всегда надёжный магазин, спасибо!',
        date: '3 мая 2025', verified: true, playtime: '55 часов', helpful: 34, platform: 'PS5',
      },
    ],
    faq: [
      { id: 'f1', question: 'Это Global версия?', answer: 'Да, Black Myth: Wukong — глобальная версия без региональных ограничений. Доступна на русском языке.' },
      { id: 'f2', question: 'Нужен ли мощный ПК?', answer: 'Игра требовательна к железу из-за Unreal Engine 5. Рекомендуем минимум RTX 2060. Для Ray Tracing нужна RTX 2080+.' },
      { id: 'f3', question: 'Есть ли мультиплеер?', answer: 'Нет, Black Myth: Wukong — полностью одиночная игра.' },
    ],
  },
  {
    id: 'gta-vi',
    title: 'Grand Theft Auto VI',
    subtitle: 'Standard Edition',
    price: 479000,
    image: 'https://picsum.photos/seed/gtavi/400/550',
    screenshots: [
      'https://picsum.photos/seed/gtavi_s1/800/450',
      'https://picsum.photos/seed/gtavi_s2/800/450',
      'https://picsum.photos/seed/gtavi_s3/800/450',
    ],
    category: 'openworld',
    platform: ['PS5', 'Xbox'],
    rating: 5.0,
    reviews: 2140,
    badge: 'preorder',
    inStock: true,
    preorder: true,
    featured: true,
    developer: 'Rockstar Games',
    releaseDate: '2025-05-26',
    deliveryType: 'manual_delivery',
    deliveryTime: 'В день выхода',
    deliveryDescription: 'Предзаказ. После релиза 26 мая 2025 менеджер вручную обработает заказ и доставит код активации на ваш email.',
    description: 'Величайший открытый мир в истории видеоигр. Возвращение в Vice City — два протагониста, гиперреализм и новое поколение GTA Online. Предзаказ открыт.',
    features: ['Vice City', 'Два протагониста', 'GTA Online 2.0', 'Гиперреализм', 'Новое поколение'],
    tags: ['openworld', 'crime', 'rockstar', 'preorder'],
  },
  {
    id: 'baldurs-gate-3',
    title: "Baldur's Gate 3",
    subtitle: 'Deluxe Edition',
    price: 279000,
    originalPrice: 329000,
    discount: 15,
    image: 'https://picsum.photos/seed/bg3/400/550',
    screenshots: [
      'https://picsum.photos/seed/bg3_s1/800/450',
      'https://picsum.photos/seed/bg3_s2/800/450',
      'https://picsum.photos/seed/bg3_s3/800/450',
      'https://picsum.photos/seed/bg3_s4/800/450',
    ],
    category: 'rpg',
    platform: ['Steam', 'PS5'],
    rating: 4.9,
    reviews: 3445,
    badge: 'hot',
    inStock: true,
    developer: 'Larian Studios',
    releaseDate: '2023-08-03',
    deliveryType: 'instant',
    description: 'Лучшая RPG 2023 года. Тысячи часов контента, бесконечные возможности выбора, кооператив на 4 игрока. Настоящее произведение искусства жанра.',
    features: ['Turn-based Combat', 'Co-op 4 игрока', 'D&D система', 'Моды Steam', '200+ часов'],
    tags: ['rpg', 'fantasy', 'turnbased', 'larian'],
  },
  {
    id: 'cod-mw3',
    title: 'Call of Duty',
    subtitle: 'Modern Warfare III',
    price: 189000,
    originalPrice: 249000,
    discount: 24,
    image: 'https://picsum.photos/seed/codmw3/400/550',
    screenshots: [
      'https://picsum.photos/seed/codmw3_s1/800/450',
      'https://picsum.photos/seed/codmw3_s2/800/450',
      'https://picsum.photos/seed/codmw3_s3/800/450',
    ],
    category: 'multiplayer',
    platform: ['Steam', 'PS5', 'Xbox'],
    rating: 4.2,
    reviews: 8920,
    badge: 'sale',
    inStock: true,
    developer: 'Sledgehammer Games',
    releaseDate: '2023-11-10',
    deliveryType: 'instant',
    description: 'Вернитесь на поля сражений с новым арсеналом, 16 ремастеренными картами MW2 и режимами. Warzone 3 включён в поставку.',
    features: ['16 карт MW2', 'Warzone', 'Zombies', 'Campaign', 'Cross-play'],
    tags: ['fps', 'shooter', 'multiplayer', 'activision'],
  },
  {
    id: 'fc-25',
    title: 'EA Sports FC 25',
    subtitle: 'Ultimate Edition',
    price: 219000,
    image: 'https://picsum.photos/seed/fc25_cover/400/550',
    screenshots: [
      'https://picsum.photos/seed/fc25_s1/800/450',
      'https://picsum.photos/seed/fc25_s2/800/450',
      'https://picsum.photos/seed/fc25_s3/800/450',
    ],
    category: 'sports',
    platform: ['EA App', 'PS5', 'Xbox'],
    rating: 4.3,
    reviews: 6780,
    badge: 'new',
    inStock: true,
    developer: 'EA Sports',
    releaseDate: '2024-09-27',
    deliveryType: 'instant',
    deliveryDescription: 'Ключ активации EA App отправляется на email сразу после оплаты. Активируйте его в приложении EA.',
    description: 'Новый сезон Football Club — улучшенная физика, FC IQ система тактик, Ultimate Team и Women\'s Football впервые с реальными лицензиями.',
    features: ['FC IQ Tactics', 'Ultimate Team', 'Women\'s Football', 'Career Mode', 'VOLTA'],
    tags: ['sports', 'football', 'ea', 'ultimate-team'],
  },
  {
    id: 'fc-26',
    title: 'EA Sports FC 26',
    subtitle: 'Standard Edition',
    price: 399000,
    image: 'https://picsum.photos/seed/fc26_cover/400/550',
    screenshots: [
      'https://picsum.photos/seed/fc26_s1/800/450',
      'https://picsum.photos/seed/fc26_s2/800/450',
    ],
    category: 'sports',
    platform: ['EA App', 'PS5', 'Xbox'],
    rating: 4.5,
    reviews: 0,
    badge: 'preorder',
    inStock: true,
    preorder: true,
    developer: 'EA Sports',
    releaseDate: '2025-09-26',
    deliveryType: 'telegram_activation',
    deliveryTime: 'В день релиза (26 сен 2025)',
    deliveryDescription: 'Предзаказ FC 26. В день выхода менеджер свяжется с вами в Telegram и активирует игру на вашем аккаунте EA.',
    description: 'Следующее поколение EA Sports FC. Новый движок, улучшенная анимация, революционный Ultimate Team. Предзаказ уже открыт — получите бонус Early Access на 3 дня.',
    features: ['Early Access 3 дня', 'Новый движок', 'Ultimate Team 26', 'Career Mode', 'FC IQ 2.0'],
    tags: ['sports', 'football', 'ea', 'preorder'],
  },
  {
    id: 'resident-evil-4',
    title: 'Resident Evil 4',
    subtitle: 'Remake Gold Edition',
    price: 199000,
    originalPrice: 249000,
    discount: 20,
    image: 'https://picsum.photos/seed/re4/400/550',
    screenshots: [
      'https://picsum.photos/seed/re4_s1/800/450',
      'https://picsum.photos/seed/re4_s2/800/450',
      'https://picsum.photos/seed/re4_s3/800/450',
      'https://picsum.photos/seed/re4_s4/800/450',
    ],
    category: 'horror',
    platform: ['Steam', 'PS5', 'Xbox'],
    rating: 4.8,
    reviews: 2156,
    badge: 'sale',
    inStock: true,
    developer: 'Capcom',
    releaseDate: '2023-03-24',
    deliveryType: 'instant',
    description: 'Культовый survival horror переосмыслён для нового поколения. Фотореалистичная графика на RE Engine, расширенный контент и VR Mode для PS VR2.',
    features: ['RE Engine', 'Survival Horror', 'Separate Ways DLC', 'VR Mode PS VR2', 'Mercenaries Mode'],
    tags: ['horror', 'survival', 'capcom', 'remake'],
  },
  {
    id: 'forza-horizon-5',
    title: 'Forza Horizon 5',
    subtitle: 'Premium Bundle',
    price: 229000,
    image: 'https://picsum.photos/seed/forza5/400/550',
    screenshots: [
      'https://picsum.photos/seed/forza5_s1/800/450',
      'https://picsum.photos/seed/forza5_s2/800/450',
      'https://picsum.photos/seed/forza5_s3/800/450',
      'https://picsum.photos/seed/forza5_s4/800/450',
    ],
    category: 'racing',
    platform: ['Steam', 'Xbox'],
    rating: 4.7,
    reviews: 4321,
    badge: 'exclusive',
    inStock: true,
    developer: 'Playground Games',
    releaseDate: '2021-11-09',
    deliveryType: 'instant',
    description: 'Лучшая гоночная игра всех времён. Мексика, более 500 автомобилей, смена сезонов и безграничная свобода исследования. Premium Bundle включает все Car Pass.',
    features: ['500+ автомобилей', 'Open World Мексика', 'Car Pass', 'Online Co-op', 'Смена сезонов'],
    tags: ['racing', 'openworld', 'xbox', 'microsoft'],
  },
];

export const trendingProducts = products.filter(p => p.featured).slice(0, 6);
export const dailyDeals = products.filter(p => p.discount && p.discount > 0);
export const newReleases = products.filter(p => p.badge === 'new' || p.badge === 'hot');
export const preorderProducts = products.filter(p => p.preorder);

export const mysteryCases: MysteryCase[] = [
  {
    id: 'silver',
    title: 'Серебряный Кейс',
    price: 49000,
    image: 'https://picsum.photos/seed/case-silver/300/300',
    items: ['Случайная игра', 'Скидка 20%', 'Arcane Coins x50'],
    color: 'from-gray-400 to-gray-600',
  },
  {
    id: 'gold',
    title: 'Золотой Кейс',
    price: 99000,
    image: 'https://picsum.photos/seed/case-gold/300/300',
    items: ['AAA игра', 'DLC бонус', 'Arcane Coins x150'],
    color: 'from-yellow-400 to-amber-600',
  },
  {
    id: 'arcane',
    title: 'Arcane Кейс',
    price: 199000,
    image: 'https://picsum.photos/seed/case-phantom/300/300',
    items: ['Эксклюзивная игра', 'Годовой пропуск', 'Arcane Coins x500'],
    color: 'from-purple-500 to-cyan-500',
  },
];

export const reviews: Review[] = [
  {
    id: '1',
    author: 'Бобур Хасанов',
    avatar: 'https://picsum.photos/seed/user1/100/100',
    rating: 5,
    text: 'Arcane.uz — лучший магазин игр в Узбекистане! Мгновенная доставка ключей, хорошие цены. Elden Ring получил за 2 минуты после оплаты.',
    date: '15 мая 2025',
    verified: true,
    productName: 'Elden Ring',
  },
  {
    id: '2',
    author: 'Камила Юсупова',
    avatar: 'https://picsum.photos/seed/user2/100/100',
    rating: 5,
    text: 'Заказывала Cyberpunk 2077 — всё пришло мгновенно. Поддержка в Telegram ответила за 5 минут. Очень довольна!',
    date: '10 мая 2025',
    verified: true,
    productName: 'Cyberpunk 2077',
  },
  {
    id: '3',
    author: 'Алишер Каримов',
    avatar: 'https://picsum.photos/seed/user3/100/100',
    rating: 5,
    text: 'Покупаю здесь уже год. Mystery Cases — это огонь! Получил GTA V и ещё 3 игры за цену одного кейса.',
    date: '5 мая 2025',
    verified: true,
    productName: 'Arcane Кейс',
  },
  {
    id: '4',
    author: 'Нилуфар Рашидова',
    avatar: 'https://picsum.photos/seed/user4/100/100',
    rating: 4,
    text: 'Отличный сервис и красивый сайт. Arcane Coins выгодная система — накопила и взяла BG3 со скидкой 30%.',
    date: '1 мая 2025',
    verified: true,
    productName: "Baldur's Gate 3",
  },
  {
    id: '5',
    author: 'Жавлон Мирзаев',
    avatar: 'https://picsum.photos/seed/user5/100/100',
    rating: 5,
    text: 'Лучший магазин! Купил Forza Horizon 5 на Xbox — ключ пришёл мгновенно. Буду постоянным покупателем.',
    date: '28 апреля 2025',
    verified: true,
    productName: 'Forza Horizon 5',
  },
  {
    id: '6',
    author: 'Дилноза Турсунова',
    avatar: 'https://picsum.photos/seed/user6/100/100',
    rating: 5,
    text: 'Arcane.uz — это отдельная эстетика! Купила FC 25 для мужа на день рождения, очень удобно оплачивать через Payme.',
    date: '22 апреля 2025',
    verified: true,
    productName: 'EA Sports FC 25',
  },
];

export const platforms = ['Steam', 'Epic Games', 'Ubisoft Connect', 'EA App', 'PS5', 'Xbox'];

export const priceRanges = [
  { label: 'До 100 000 сум',        min: 0,      max: 100000 },
  { label: '100 000 — 200 000 сум', min: 100000, max: 200000 },
  { label: '200 000 — 300 000 сум', min: 200000, max: 300000 },
  { label: 'Свыше 300 000 сум',     min: 300000, max: Infinity },
];

export const PRICE_MIN = 0;
export const PRICE_MAX = 500000;
